# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-04 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('codigo', models.CharField(help_text='Codigo de la materia', max_length=7, primary_key=True, serialize=False)),
                ('nombre', models.TextField(help_text='Nombre de la materia')),
            ],
        ),
    ]
