# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-04 20:58
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Materia', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='materia',
            name='usuario',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
