# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-04 05:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Horario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idHorario', models.IntegerField()),
                ('dia', models.DateTimeField()),
                ('horaInicio', models.DateTimeField(help_text='Hora en que comienza el horario')),
                ('horaFinal', models.DateTimeField(help_text='Hora en que finaliza el horario')),
            ],
        ),
    ]
