# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-06 17:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Materia', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Horario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutoria',
            name='estudiante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='estudiante', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutoria',
            name='horario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Horario.Horario'),
        ),
        migrations.AddField(
            model_name='tutoria',
            name='materia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Materia.Materia'),
        ),
        migrations.AddField(
            model_name='tutoria',
            name='profesor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profesor', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='horario',
            name='usuario',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
