# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-07 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Horario', '0003_auto_20180606_1235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='horario',
            name='horaFinal',
            field=models.TextField(choices=[('06:00', '06:00'), ('07:00', '07:00'), ('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00')], default='-------', help_text='Hora en que finaliza el horario'),
        ),
        migrations.AlterField(
            model_name='horario',
            name='horaInicio',
            field=models.TextField(choices=[('06:00', '06:00'), ('07:00', '07:00'), ('08:00', '08:00'), ('09:00', '09:00'), ('10:00', '10:00'), ('11:00', '11:00'), ('12:00', '12:00'), ('13:00', '13:00'), ('14:00', '14:00'), ('15:00', '15:00'), ('16:00', '16:00'), ('17:00', '17:00'), ('18:00', '18:00'), ('19:00', '19:00'), ('20:00', '20:00'), ('21:00', '21:00'), ('22:00', '22:00')], default='-------', help_text='Hora en que comienza el horario'),
        ),
    ]
