-- MySQL Script generated by MySQL Workbench
-- Wed May  9 10:11:48 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema SistemaTutorias
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema SistemaTutorias
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `SistemaTutorias` DEFAULT CHARACTER SET utf8 ;
USE `SistemaTutorias` ;

-- -----------------------------------------------------
-- Table `SistemaTutorias`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaTutorias`.`Usuario` (
  `user` INT NOT NULL,
  `password` VARCHAR(12) NOT NULL,
  PRIMARY KEY (`user`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTutorias`.`Persona`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaTutorias`.`Persona` (
  `identificacion` VARCHAR(10) NOT NULL,
  `nombre` VARCHAR(20) NOT NULL,
  `apellido` VARCHAR(20) NOT NULL,
  `correo` VARCHAR(45) NOT NULL,
  `Usuario_user` INT NOT NULL,
  PRIMARY KEY (`identificacion`, `Usuario_user`),
  INDEX `fk_Persona_Usuario_idx` (`Usuario_user` ASC),
  CONSTRAINT `fk_Persona_Usuario`
    FOREIGN KEY (`Usuario_user`)
    REFERENCES `SistemaTutorias`.`Usuario` (`user`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTutorias`.`Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaTutorias`.`Estudiante` (
  `codigo` VARCHAR(10) NOT NULL,
  `semestre` VARCHAR(2) CHARACTER SET 'utf8' COLLATE 'utf8_spanish2_ci' NOT NULL,
  `Persona_identificacion` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`codigo`, `Persona_identificacion`),
  INDEX `fk_Estudiante_Persona1_idx` (`Persona_identificacion` ASC),
  CONSTRAINT `fk_Estudiante_Persona1`
    FOREIGN KEY (`Persona_identificacion`)
    REFERENCES `SistemaTutorias`.`Persona` (`identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTutorias`.`Programa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaTutorias`.`Programa` (
  `idPrograma` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idPrograma`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTutorias`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaTutorias`.`Profesor` (
  `profesion` VARCHAR(45) NULL,
  `especialidad` VARCHAR(45) NULL,
  `Persona_identificacion` VARCHAR(10) NOT NULL,
  `Programa_idPrograma` INT NOT NULL,
  PRIMARY KEY (`Persona_identificacion`, `Programa_idPrograma`),
  INDEX `fk_Profesor_Programa1_idx` (`Programa_idPrograma` ASC),
  CONSTRAINT `fk_Profesor_Persona1`
    FOREIGN KEY (`Persona_identificacion`)
    REFERENCES `SistemaTutorias`.`Persona` (`identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profesor_Programa1`
    FOREIGN KEY (`Programa_idPrograma`)
    REFERENCES `SistemaTutorias`.`Programa` (`idPrograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTutorias`.`Programa_has_Estudiante`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaTutorias`.`Programa_has_Estudiante` (
  `Programa_idPrograma` INT NOT NULL,
  `Estudiante_codigo` VARCHAR(10) NOT NULL,
  `Estudiante_Persona_identificacion` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`Programa_idPrograma`, `Estudiante_codigo`, `Estudiante_Persona_identificacion`),
  INDEX `fk_Programa_has_Estudiante_Estudiante1_idx` (`Estudiante_codigo` ASC, `Estudiante_Persona_identificacion` ASC),
  INDEX `fk_Programa_has_Estudiante_Programa1_idx` (`Programa_idPrograma` ASC),
  CONSTRAINT `fk_Programa_has_Estudiante_Programa1`
    FOREIGN KEY (`Programa_idPrograma`)
    REFERENCES `SistemaTutorias`.`Programa` (`idPrograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Programa_has_Estudiante_Estudiante1`
    FOREIGN KEY (`Estudiante_codigo` , `Estudiante_Persona_identificacion`)
    REFERENCES `SistemaTutorias`.`Estudiante` (`codigo` , `Persona_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTutorias`.`Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaTutorias`.`Materia` (
  `idMateria` VARCHAR(8) NOT NULL,
  `nombre` VARCHAR(30) NOT NULL,
  `Programa_idPrograma` INT NOT NULL,
  PRIMARY KEY (`idMateria`, `Programa_idPrograma`),
  INDEX `fk_Materia_Programa1_idx` (`Programa_idPrograma` ASC),
  CONSTRAINT `fk_Materia_Programa1`
    FOREIGN KEY (`Programa_idPrograma`)
    REFERENCES `SistemaTutorias`.`Programa` (`idPrograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTutorias`.`Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaTutorias`.`Horario` (
  `idHorario` INT NOT NULL AUTO_INCREMENT,
  `dia` INT NOT NULL,
  `horarioInicio` VARCHAR(5) NOT NULL,
  `horarioFinal` VARCHAR(5) NOT NULL,
  PRIMARY KEY (`idHorario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTutorias`.`Profesor_has_Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaTutorias`.`Profesor_has_Horario` (
  `Profesor_Persona_identificacion` VARCHAR(10) NOT NULL,
  `Horario_idHorario` INT NOT NULL,
  PRIMARY KEY (`Profesor_Persona_identificacion`, `Horario_idHorario`),
  INDEX `fk_Profesor_has_Horario_Horario1_idx` (`Horario_idHorario` ASC),
  INDEX `fk_Profesor_has_Horario_Profesor1_idx` (`Profesor_Persona_identificacion` ASC),
  CONSTRAINT `fk_Profesor_has_Horario_Profesor1`
    FOREIGN KEY (`Profesor_Persona_identificacion`)
    REFERENCES `SistemaTutorias`.`Profesor` (`Persona_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profesor_has_Horario_Horario1`
    FOREIGN KEY (`Horario_idHorario`)
    REFERENCES `SistemaTutorias`.`Horario` (`idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTutorias`.`Materia_has_Horario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaTutorias`.`Materia_has_Horario` (
  `Materia_idMateria` VARCHAR(8) NOT NULL,
  `Materia_Programa_idPrograma` INT NOT NULL,
  `Horario_idHorario` INT NOT NULL,
  PRIMARY KEY (`Materia_idMateria`, `Materia_Programa_idPrograma`, `Horario_idHorario`),
  INDEX `fk_Materia_has_Horario_Horario1_idx` (`Horario_idHorario` ASC),
  INDEX `fk_Materia_has_Horario_Materia1_idx` (`Materia_idMateria` ASC, `Materia_Programa_idPrograma` ASC),
  CONSTRAINT `fk_Materia_has_Horario_Materia1`
    FOREIGN KEY (`Materia_idMateria` , `Materia_Programa_idPrograma`)
    REFERENCES `SistemaTutorias`.`Materia` (`idMateria` , `Programa_idPrograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Materia_has_Horario_Horario1`
    FOREIGN KEY (`Horario_idHorario`)
    REFERENCES `SistemaTutorias`.`Horario` (`idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTutorias`.`Tutoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaTutorias`.`Tutoria` (
  `idTutoria` INT NOT NULL AUTO_INCREMENT,
  `persCodigo_Persona` VARCHAR(10) NOT NULL,
  `idHorario_Horario` INT NOT NULL,
  `materiaCodigo_Materia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idTutoria`, `persCodigo_Persona`, `idHorario_Horario`, `materiaCodigo_Materia`),
  INDEX `Tutoria_Materia_idx` (`materiaCodigo_Materia` ASC),
  INDEX `TutoriaHorario_idx` (`idHorario_Horario` ASC),
  INDEX `TutoriaPersona_idx` (`persCodigo_Persona` ASC),
  CONSTRAINT `Tutoria_Materia`
    FOREIGN KEY (`materiaCodigo_Materia`)
    REFERENCES `SistemaTutorias`.`Materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TutoriaPersona`
    FOREIGN KEY (`persCodigo_Persona`)
    REFERENCES `SistemaTutorias`.`Profesor` (`Persona_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `TutoriaHorario`
    FOREIGN KEY (`idHorario_Horario`)
    REFERENCES `SistemaTutorias`.`Horario` (`idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTutorias`.`Reporte`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaTutorias`.`Reporte` (
  `idReporte` INT NOT NULL,
  `idProfesor` VARCHAR(10) NOT NULL,
  `idEstudiante` VARCHAR(10) NOT NULL,
  `idHorario` INT NOT NULL,
  `idMateria` VARCHAR(8) NOT NULL,
  PRIMARY KEY (`idReporte`, `idProfesor`, `idEstudiante`, `idHorario`, `idMateria`),
  INDEX `idMateria_FK_idx` (`idMateria` ASC),
  INDEX `idEstudiante_idx` (`idEstudiante` ASC),
  INDEX `idHorario_idx` (`idHorario` ASC),
  INDEX `idProfesor_idx` (`idProfesor` ASC),
  CONSTRAINT `idMateria_FK`
    FOREIGN KEY (`idMateria`)
    REFERENCES `SistemaTutorias`.`Materia` (`idMateria`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idEstudiante`
    FOREIGN KEY (`idEstudiante`)
    REFERENCES `SistemaTutorias`.`Estudiante` (`codigo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idHorario`
    FOREIGN KEY (`idHorario`)
    REFERENCES `SistemaTutorias`.`Horario` (`idHorario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idProfesor`
    FOREIGN KEY (`idProfesor`)
    REFERENCES `SistemaTutorias`.`Profesor` (`Persona_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTutorias`.`Estudiante_has_Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaTutorias`.`Estudiante_has_Materia` (
  `Estudiante_codigo` VARCHAR(10) NOT NULL,
  `Estudiante_Persona_identificacion` VARCHAR(10) NOT NULL,
  `Materia_idMateria` VARCHAR(8) NOT NULL,
  `Materia_Programa_idPrograma` INT NOT NULL,
  PRIMARY KEY (`Estudiante_codigo`, `Estudiante_Persona_identificacion`, `Materia_idMateria`, `Materia_Programa_idPrograma`),
  INDEX `fk_Estudiante_has_Materia_Materia1_idx` (`Materia_idMateria` ASC, `Materia_Programa_idPrograma` ASC),
  INDEX `fk_Estudiante_has_Materia_Estudiante1_idx` (`Estudiante_codigo` ASC, `Estudiante_Persona_identificacion` ASC),
  CONSTRAINT `fk_Estudiante_has_Materia_Estudiante1`
    FOREIGN KEY (`Estudiante_codigo` , `Estudiante_Persona_identificacion`)
    REFERENCES `SistemaTutorias`.`Estudiante` (`codigo` , `Persona_identificacion`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Estudiante_has_Materia_Materia1`
    FOREIGN KEY (`Materia_idMateria` , `Materia_Programa_idPrograma`)
    REFERENCES `SistemaTutorias`.`Materia` (`idMateria` , `Programa_idPrograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `SistemaTutorias`.`Profesor_has_Materia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `SistemaTutorias`.`Profesor_has_Materia` (
  `Profesor_Persona_identificacion` VARCHAR(10) NOT NULL,
  `Profesor_Programa_idPrograma` INT NOT NULL,
  `Materia_idMateria` VARCHAR(8) NOT NULL,
  `Materia_Programa_idPrograma` INT NOT NULL,
  PRIMARY KEY (`Profesor_Persona_identificacion`, `Profesor_Programa_idPrograma`, `Materia_idMateria`, `Materia_Programa_idPrograma`),
  INDEX `fk_Profesor_has_Materia_Materia1_idx` (`Materia_idMateria` ASC, `Materia_Programa_idPrograma` ASC),
  INDEX `fk_Profesor_has_Materia_Profesor1_idx` (`Profesor_Persona_identificacion` ASC, `Profesor_Programa_idPrograma` ASC),
  CONSTRAINT `fk_Profesor_has_Materia_Profesor1`
    FOREIGN KEY (`Profesor_Persona_identificacion` , `Profesor_Programa_idPrograma`)
    REFERENCES `SistemaTutorias`.`Profesor` (`Persona_identificacion` , `Programa_idPrograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Profesor_has_Materia_Materia1`
    FOREIGN KEY (`Materia_idMateria` , `Materia_Programa_idPrograma`)
    REFERENCES `SistemaTutorias`.`Materia` (`idMateria` , `Programa_idPrograma`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
