# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2018-06-04 05:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('TipoUsuario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.CharField(max_length=12, primary_key=True, serialize=False)),
                ('nombres', models.TextField()),
                ('apellidos', models.TextField()),
                ('correo', models.EmailField(max_length=254)),
                ('tipoUsuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TipoUsuario.TipoUsuario')),
            ],
        ),
    ]
